version: 2
updates:
  - package-ecosystem: "docker"
    directory: "/exporter"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
    target-branch: "main"
    commit-message:
      prefix: "chore(deps)"
